# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0008_registration_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phoneno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='phoneno',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POC.Registration'),
        ),
    ]
