# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('POC', '0010_auto_20191122_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
